version: "3.8"
services:
  web-server_prod:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./:/var/www/html/"
      - "/var/www/html/Tests"
    ports:
      - "8000:80"
  composer-installation_prod:
    container_name: composer-installation_prod
    image: composer:2.4.4
    volumes:
      - "./:/app"
    command: composer install --no-dev --prefer-source