version: "3.8"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./:/var/www/html/"
    ports:
      - "8080:80"
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - "./:/app"
    command: composer install --prefer-source