version: "3.8"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./:/var/www/html/"
    ports:
      - "8281:80"

  composer-installation:
    image: composer:2.4.4
    volumes:
      - "./:/app"
    command: composer install